# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestDefaultSuite():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_addtocart(self):
        self.driver.get("https://www.saucedemo.com/")
        self.driver.set_window_size(1046, 1034)
        WebDriverWait(self.driver, 30).until(
            expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "*[data-test=\"username\"]")))
        self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"username\"]").click()
        self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"username\"]").send_keys("standard_user")
        WebDriverWait(self.driver, 30).until(
            expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "*[data-test=\"password\"]")))
        self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"password\"]").click()
        self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"password\"]").send_keys("secret_sauce")
        self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"login-button\"]").click()
        WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located(
            (By.CSS_SELECTOR, "*[data-test=\"add-to-cart-sauce-labs-bike-light\"]")))
        self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"add-to-cart-sauce-labs-bike-light\"]").click()
        self.driver.find_element(By.LINK_TEXT, "1").click()
        self.vars["1"] = len(self.driver.find_elements(By.CSS_SELECTOR, "*[class=\"cart_list\"]"))
        self.driver.close()

    def test_addtocart3items(self):
        self.driver.get("https://www.saucedemo.com/")
        self.driver.set_window_size(1046, 1034)
        WebDriverWait(self.driver, 30).until(
            expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "*[data-test=\"username\"]")))
        self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"username\"]").click()
        self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"username\"]").send_keys("standard_user")
        WebDriverWait(self.driver, 30).until(
            expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "*[data-test=\"password\"]")))
        self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"password\"]").click()
        self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"password\"]").send_keys("secret_sauce")
        self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"login-button\"]").click()
        WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located(
            (By.CSS_SELECTOR, "*[data-test=\"add-to-cart-sauce-labs-bike-light\"]")))
        self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"add-to-cart-sauce-labs-bike-light\"]").click()
        self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"add-to-cart-sauce-labs-backpack\"]").click()
        self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"add-to-cart-sauce-labs-bolt-t-shirt\"]").click()
        self.driver.find_element(By.LINK_TEXT, "3").click()
        self.vars["3"] = len(self.driver.find_elements(By.CSS_SELECTOR, "*[class=\"cart_list\"]"))
        self.driver.close()

    def test_order(self):
        self.driver.get("https://www.saucedemo.com/")
        self.driver.set_window_size(1046, 1034)
        WebDriverWait(self.driver, 30).until(
            expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "*[data-test=\"username\"]")))
        self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"username\"]").click()
        self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"username\"]").send_keys("standard_user")
        WebDriverWait(self.driver, 30).until(
            expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "*[data-test=\"password\"]")))
        self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"password\"]").click()
        self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"password\"]").send_keys("secret_sauce")
        self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"login-button\"]").click()
        WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located(
            (By.CSS_SELECTOR, "*[data-test=\"add-to-cart-sauce-labs-bike-light\"]")))
        self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"add-to-cart-sauce-labs-bike-light\"]").click()
        self.driver.find_element(By.LINK_TEXT, "1").click()
        self.vars["1"] = len(self.driver.find_elements(By.CSS_SELECTOR, "*[class=\"cart_list\"]"))
        self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"checkout\"]").click()
        WebDriverWait(self.driver, 30).until(
            expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "*[data-test=\"firstName\"]")))
        self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"firstName\"]").click()
        self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"firstName\"]").send_keys("kagan")
        WebDriverWait(self.driver, 30).until(
            expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "*[data-test=\"lastName\"]")))
        self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"lastName\"]").click()
        self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"lastName\"]").send_keys("efe")
        WebDriverWait(self.driver, 30).until(
            expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "*[data-test=\"postalCode\"]")))
        self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"postalCode\"]").click()
        self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"postalCode\"]").send_keys("06312")
        WebDriverWait(self.driver, 30).until(
            expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "*[data-test=\"continue\"]")))
        self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"continue\"]").click()
        WebDriverWait(self.driver, 30).until(
            expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "*[data-test=\"finish\"]")))
        self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"finish\"]").click()
        WebDriverWait(self.driver, 30).until(
            expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "*[data-test=\"back-to-products\"]")))
        self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"back-to-products\"]").click()
        self.driver.close()

    def test_removefromcart(self):
        self.driver.get("https://www.saucedemo.com/")
        self.driver.set_window_size(1046, 1034)
        WebDriverWait(self.driver, 30).until(
            expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "*[data-test=\"username\"]")))
        self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"username\"]").click()
        self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"username\"]").send_keys("standard_user")
        WebDriverWait(self.driver, 30).until(
            expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "*[data-test=\"password\"]")))
        self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"password\"]").click()
        self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"password\"]").send_keys("secret_sauce")
        self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"login-button\"]").click()
        WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located(
            (By.CSS_SELECTOR, "*[data-test=\"add-to-cart-sauce-labs-bike-light\"]")))
        self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"add-to-cart-sauce-labs-bike-light\"]").click()
        self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"add-to-cart-sauce-labs-backpack\"]").click()
        self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"add-to-cart-sauce-labs-bolt-t-shirt\"]").click()
        self.driver.find_element(By.LINK_TEXT, "3").click()
        self.vars["3"] = len(self.driver.find_elements(By.CSS_SELECTOR, "*[class=\"cart_list\"]"))
        self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"remove-sauce-labs-bike-light\"]").click()
        self.vars["2"] = len(self.driver.find_elements(By.CSS_SELECTOR, "*[class=\"cart_list\"]"))
        self.driver.close()

    def test_invalidloginwait(self):
        self.driver.get("https://www.saucedemo.com/")
        self.driver.set_window_size(1046, 1034)
        WebDriverWait(self.driver, 30).until(
            expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "*[data-test=\"username\"]")))
        self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"username\"]").click()
        self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"username\"]").send_keys("1")
        WebDriverWait(self.driver, 30).until(
            expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "*[data-test=\"password\"]")))
        self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"password\"]").click()
        self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"password\"]").send_keys("1")
        self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"login-button\"]").click()
        assert self.driver.find_element(By.CSS_SELECTOR,
                                        "*[data-test=\"error\"]").text == "Epic sadface: Username and password do not match any user in this service"
        self.driver.close()

    def test_lockedoutlogin(self):
        self.driver.get("https://www.saucedemo.com/")
        self.driver.set_window_size(1046, 1034)
        WebDriverWait(self.driver, 30).until(
            expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "*[data-test=\"username\"]")))
        self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"username\"]").click()
        self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"username\"]").send_keys("locked_out_user")
        WebDriverWait(self.driver, 30).until(
            expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "*[data-test=\"password\"]")))
        self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"password\"]").click()
        self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"password\"]").send_keys("secret_sauce")
        self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"login-button\"]").click()
        assert self.driver.find_element(By.CSS_SELECTOR,
                                        "*[data-test=\"error\"]").text == "Epic sadface: Sorry, this user has been locked out."
        self.driver.close()

    def test_logintest(self):
        self.driver.get("https://www.saucedemo.com/")
        self.driver.set_window_size(1046, 1034)
        WebDriverWait(self.driver, 30).until(
            expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "*[data-test=\"username\"]")))
        self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"username\"]").click()
        self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"username\"]").send_keys("standard_user")
        WebDriverWait(self.driver, 30).until(
            expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "*[data-test=\"password\"]")))
        self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"password\"]").click()
        self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"password\"]").send_keys("secret_sauce")
        self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"login-button\"]").click()
        self.vars["6"] = len(self.driver.find_elements(By.CSS_SELECTOR, "*[class=\"inventory_list\"]"))
        self.driver.close()

    def test_passwordrequired(self):
        self.driver.get("https://www.saucedemo.com/")
        self.driver.set_window_size(1046, 1034)
        WebDriverWait(self.driver, 30).until(
            expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "*[data-test=\"username\"]")))
        self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"username\"]").send_keys("standard_user")
        self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"login-button\"]").click()
        assert self.driver.find_element(By.CSS_SELECTOR,
                                        "*[data-test=\"error\"]").text == "Epic sadface: Password is required"
        self.driver.close()

    def test_usernamepasswordrequired(self):
        self.driver.get("https://www.saucedemo.com/")
        self.driver.set_window_size(1046, 1034)
        WebDriverWait(self.driver, 30).until(
            expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "*[data-test=\"login-button\"]")))
        self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"login-button\"]").click()
        assert self.driver.find_element(By.CSS_SELECTOR,
                                        "*[data-test=\"error\"]").text == "Epic sadface: Username is required"
        self.driver.close()

    def test_usernamerequired(self):
        self.driver.get("https://www.saucedemo.com/")
        self.driver.set_window_size(1046, 1034)
        WebDriverWait(self.driver, 30).until(
            expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "*[data-test=\"password\"]")))
        self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"password\"]").send_keys("secred_sauce")
        self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"login-button\"]").click()
        assert self.driver.find_element(By.CSS_SELECTOR,
                                        "*[data-test=\"error\"]").text == "Epic sadface: Username is required"
        self.driver.close()
